### ISSUE TITLE
Run PRECAST with SpatialExperiment

### ISSUE THREAD

**Issue by boyiguo1** [feiyoung/PRECAST#1]
Because the `PRECAST` pipeline is based on `Seurat`, which creates difficulty for bio conductor users who's familiar with `spatialExperiment`.

I wrote these wrapper functions to convert a spatialExperiment (possibly multiple samples in the same object) to seuraList for anyone who wants to use. Please find them in https://github.com/feiyoung/PRECAST_Analysis/issues/1#issuecomment-1261295891.

**Comment by feiyoung** [comment]
Hi Boyi. Thank you for your provided wrapper function for spatialExperiment and valuable feedback. We will  optimize the package to make it easy-used for users, such as adding the inerface for spatialExperiment and SingleCellExperiment, and writing more detailed vigenettes. Thank you again!

**Comment by boyiguo1** [comment]
Haha, just to be clear, I didn't mean to push you to do anything. I appreciate you are working on such a valuable method/tool.
