### ISSUE TITLE
Error when running IntegrateSpaData

### ISSUE THREAD

**Issue by agelber-ucsd** [feiyoung/PRECAST#10]
Hi,

I am trying to run IntegrateSpaData and after downloading the newest version to be able to include biological covariates I am getting the following error.:

Error in `[[<-.data.frame`(`*tmp*`, i, value = c(1084623L, 5715162L, 1110488L,  : 
  replacement has 8768019 rows, data has 224821

Any idea why this my be happening? It happens at this line:

hX <- get_correct_exp(XList, PRECASTObj@resList$Rf, houseKeep = houseKeep, 
    q_unwanted = min(10, length(houseKeep)), covariateList = covariateList)

It works without the covariates included but once included I get the error above.

-Alon

Update: I'm not sure if you're also seeing this error but I'm getting it at the linear model step:
lm1 <- lm(X0 ~ 0 + cbind(M0, Rf))

**Comment by feiyoung** [comment]
Thank you for bringing this bug to our attention. We are pleased to inform you that it has been resolved in the development version of PRECAST on GitHub (PRECAST version 1.6.1). We appreciate your valuable contribution towards enhancing PRECAST, and thank you once again!

**Comment by agelber-ucsd** [comment]
Thanks! I realized later it had something to with factor types in the model but I'll just go ahead and install the development version. Thanks again for your prompt response!
