### ISSUE TITLE
Possible Incompatiblity with Seurat V5

### ISSUE THREAD

**Issue by boyiguo1** [feiyoung/PRECAST#12]
I wonder if you have tested your implementation with `Seurat V5`.

It seems that `Seurat V5` used a new data structure (`Assay (v5) data`, https://satijalab.org/seurat/articles/seurat5_essential_commands.html#working-with-layers) to count matrices, which seems to break your current implementation when feeding `CreatePRECASTObject` a `seuList` created using `Seurat V5`.
```R
> preobj <- CreatePRECASTObject(seuList = seuList)
Filter spots and features from Raw count data...
  |                                                  | 0 % ~calculating  Error in FUN(X[[i]], ...) : 
  no slot of name "counts" for this object of class "Assay5"
```

Specifically
```R
> seuList[[1]][["RNA"]]@counts
Error: no slot of name "counts" for this object of class "Assay5"
```

For your information, I am using `Seurat_4.9.9.9049`

**Comment by feiyoung** [comment]
Thank you for your feedback!  I'll fix it in recent days.

**Comment by feiyoung** [comment]
Now, PRECAST version 1.6.2 supports the Seurat V5. 

Thank you!
