### ISSUE TITLE
[documentation] Clarification on parallel computing

### ISSUE THREAD

**Issue by boyiguo1** [feiyoung/PRECAST#17]
Thanks for the wonderful implementation of `PRECAST`. 

I wonder if there's any documentation on which steps the parallel computing is employed. For example, does the step of fitting the PRECAST model via `PRECAST()` employ parallel computing, or only the preprocessing steps uses parallel computing.

Thank you very much.

Best,
Boyi

**Comment by feiyoung** [comment]
In the PRECAST R package, parallel computing is exclusively employed during the fitting stage of the PRECAST model through the PRECAST() function when the user specifies a range of cluster numbers (K=3:10). Each value of K triggers a dedicated thread for fitting the PRECAST model.

**Comment by boyiguo1** [comment]
Thank you for the feedback.
