### ISSUE TITLE
PRECAST IntegrateSpaData errors

### ISSUE THREAD

**Issue by anvaly** [feiyoung/PRECAST#2]
Hello, when I try to run the package I encounter the following two errors:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': Cannot find 'RNA' in this Seurat object

This stems from line 9 of IntegrateSpaData:
XList <- lapply(PRECASTObj@seulist, function(x) Matrix::t(x[["RNA"]]@data))

Is the intention of this line to use the normalized or non-normalized assay of the Seurat object? (E.g., Spatial or SCT)

If I fix this error by copying one of the existing assays (Spatial or SCT) to an assay named "RNA", I experience another error.

Error in intersect((genelist), Mouse_HK_genes$Gene) : 
  object 'Mouse_HK_genes' not found

This stems from line 24 of IntegrateSpaData:
  houseKeep <- switch(lower_species, human = {
    intersect((genelist), Mouse_HK_genes$Gene)

The script is trying to reach for the mouse gene list that wasn't defined. What is the exact purpose of this list?

**Comment by feiyoung** [comment]
Thank you for feedback. Yes, this intention of that line is to use the normalized assay. 

We have updated the function `IntegrateSpaData()` in new version 1.5 of PRECAST. You can re-install PRECAST from github by commond: remotes::install_github("feiyoung/PRECAST").

Before using PRECAST, please read our tutorial https://feiyoung.github.io/PRECAST/articles/PRECAST.BreastCancer.html; then try again. To avoid error, one user can strictly follow the step given in the tutorial.

**Comment by anvaly** [comment]
Thank you for your response! Indeed, upgrading from 1.4 to 1.5 fixed these two issues.
