### ISSUE TITLE
where can I find the PRECAST corrected gene expression data? 

### ISSUE THREAD

**Issue by abraham-abin13** [feiyoung/PRECAST#23]
In my analysis, i have an object ``preObj`` which is created after running ``IntegrateSpaData()``. ``preObj`` has an assay called "PRE_CAST". 

To access the PRECAST corrected gene expression, I am running the ``preObj[["PRE_CAST"]]$data`` command. 

Is this the correct location of the corrected gene expression?

**Comment by feiyoung** [comment]
Yes, it is.
