### ISSUE TITLE
applying psuedobulk 

### ISSUE THREAD

**Issue by abraham-abin13** [feiyoung/PRECAST#24]
Hi, 
Thank you again for a powerful package for spatial analyses. I wanted to apply psuedobulking to the PRECAST corrected gene expression matrix. However, the corrected gene expression ranges from negative to positive numbers. Many psuedobulking approaches log normalizes after aggregation. This step is not possible when there are negative expression values. Any advice on how to handle this? Thank you, 
Abin

**Comment by feiyoung** [comment]
For each gene, you can convert it to a non-negative value by subtracting the minimum value from the corrected expression values.
