### ISSUE TITLE
Request for guidance on improving clustering of matched tumor samples using PRECAST tool

### ISSUE THREAD

**Issue by AteeqMKhaliq** [feiyoung/PRECAST#9]
Hi Feiyoung,

I wanted to take a moment to express my appreciation and gratitude for the amazing work you have done in developing the PRECAST tool. Your efforts have made a significant contribution to the field of cancer research, and I am truly impressed by the capabilities and functionality of your tool.

I am writing to you regarding an issue I am facing with the clustering of matched tumor samples using your code. I have been trying to cluster the samples using the provided code on your GitHub repository, but I have not been able to get clear clusters. Please take a look at the UMAP, the clusters are not well segregated. 

I have followed the instructions carefully and have tried different parameter settings, but the clustering results are not as expected. I am particularly interested in improving the clustering of the matched tumor samples.

Could you please provide some guidance on how to improve the clustering of the matched tumor samples using your code? Do you have any suggestions or recommendations that could help me improve the clustering results?
I would greatly appreciate your help and guidance on this matter. 
Thank you very much for your time and consideration.

Sincerely,
Ateeq
[umap.pdf](https://github.com/feiyoung/PRECAST/files/11402472/umap.pdf)

**Comment by feiyoung** [comment]
I have not come across such unseparated clusters in the UMAP plot before. Can you please provide some basic information about your data, such as the platform used, number of sections, and average number of spots?

Without additional information, I can offer some suggestions that you may find helpful:

 1. You can try integrating two samples to see if they produce the same unseparated clusters in UMAP.

  2. Consider using the low-level functions to investigate more details  in the PRECAST package, such as the ICM.EM() function. You can extract the components from PRECASTObj and use them as input for this function.

take out adjacence matrix list.
AdjList <- PRECASTObj@AdjList
take out the log-normalized data from seulist.
If your default assay is RNA, use the following code.
XList <- lapply(PRECASTObj@seulist, function(x) Matrix::t(x[['RNA']]@ data))
If not, use
XList <- list()
for(i in seq_along(PRECASTObj@seulist)){
message("i=", i)
seu <- PRECASTObj@seulist[[i]]
defassy <- DefaultAssay(seu)
XList[[i]] <- Matrix::t(seu[[defassy]]@ data)
}
XList[[1]][1:4,1:5] ## check the values
hq <- 15; 
hK <- 12  ##

resList <- ICM.EM(XList, q=hq, K=hK, AdjList= AdjList, ## ICM.EM is the low-level interface for PRECAST algorithm.
platform = "Other_SRT" ,maxIter = 30,
Sigma_equal =F, coreNum=1)

Based on the results in resList, visualize the cluster component on the UMAP of hZ component; ?ICM.EM to find more details about the component in resList.

**Comment by AteeqMKhaliq** [comment]
Thanks a lot for your quick response, i have 10x Visium Spatial  FFPE samples. we have matched 40 Tumor samples. I have used the following codes.
```



library(PRECAST)
library(Seurat)

print("Loding object")
pdac <- readRDS("/Users/akhaliq/Desktop/spatial_analysis/new_st_obj/codes/pdac_new_st.rds")

image_names <- c("IU",IU1","IU2","IU4,",IU5","IU6")

print("Create an empty list to store the coordinates for each image")

coordinates_list <- list()

for (image_name in image_names) {
  pos <- GetTissueCoordinates(pdac, image = image_name)
  
  colnames(pos) <- c('row','col')
  
  coordinates_list[[image_name]] <- pos
}

coordinates_df <- do.call(rbind, coordinates_list)

row_names <- rownames(coordinates_df)
new_row_names <- gsub("^.+\\.", "", row_names)

rownames(coordinates_df) <- new_row_names

coordinates_df$sample <- NULL

head(coordinates_df)

pdac <- AddMetaData(pdac,coordinates_df)

pdac.list <- SplitObject(pdac, split.by = "orig.ident")

rm(pdac)

countList <- lapply(pdac.list, function(x) x[["Spatial"]]@counts)

metadataList <- lapply(pdac.list, function(x) x@meta.data)

M <- length(countList)
for (r in 1:M) {
    row.names(metadataList[[r]]) <- colnames(countList[[r]])
}

print("Create the Seurat list object")

seuList <- list()
for (r in 1:M) {
    seuList[[r]] <- CreateSeuratObject(counts = countList[[r]], meta.data = metadataList[[r]], project = "pdac_PRECAST")
}

pdac.list <- seuList
rm(seuList)


PRECASTObj <- CreatePRECASTObject(pdac.list, project = "PRECAST", gene.number = 2000, selectGenesMethod = "SPARK-X",
    premin.spots = 20, premin.features = 20, postmin.spots = 1, postmin.features = 10)

PRECASTObj@seulist

PRECASTObj <- AddAdjList(PRECASTObj, platform = "Visium")

PRECASTObj <- AddParSetting(PRECASTObj, Sigma_equal = FALSE, verbose = TRUE, int.model = NULL)

gc()

saveRDS(PRECASTObj,"PRECASTObj.rds")

PRECASTObj <- PRECAST(PRECASTObj, K = 10:15)

gc()

saveRDS(PRECASTObj,"PRECASTObj.rds")
resList <- PRECASTObj@resList
PRECASTObj <- selectModel(PRECASTObj)

seuInt <- IntegrateSpaData(PRECASTObj, species = "Human")

saveRDS(seuInt,"seuInt.rds")

`

```
Thanks a lot for all your help

**Comment by feiyoung** [comment]
I don't find any issues with the code you provided. However, there are some additional things you can try:

1. Use two samples and a fixed K value, such as K=12, to check whether it produces better cluster labels in the UMAP plot. If the results are satisfactory, you can then integrate more samples.

2. Use 'HVGs' to select highly variable genes:
PRECASTObj <- CreatePRECASTObject(pdac.list, project = "PRECAST", gene.number = 2000, selectGenesMethod = "HVGs", premin.spots = 20, premin.features = 20, postmin.spots = 1, postmin.features = 10)

3. Try using more genes, such as gene.number=3000.

4. Use more factors in fitting PRECAST: PRECASTObj <- PRECAST(PRECASTObj, q=30, K = 12).

**Comment by AteeqMKhaliq** [comment]
Appreciate your prompt response, I will check with 2 samples as per your suggestions and i am hoping to get good segregation. I will keep you posted. Thanks again for your help.
Regards,
Ateeq

**Comment by AteeqMKhaliq** [comment]
Hi Feiyoung, 
As per your suggestions, i have made few test runs on 2 samples and on 5 samples. The results are not what i expected, I can see that the batch effect was not corrected, do you think we should go ahead and use this clusters? Please let me know your view/suggestions to improve the quality. 
Thanks a lot for your help.
Ateeq
[samp2_umap.pdf](https://github.com/feiyoung/PRECAST/files/11414854/samp2_umap.pdf)
[pdac_5samp_umapBatch.pdf](https://github.com/feiyoung/PRECAST/files/11414855/pdac_5samp_umapBatch.pdf)
[5samps_umap.pdf](https://github.com/feiyoung/PRECAST/files/11414856/5samps_umap.pdf)
[samp2_batch_umap.pdf](https://github.com/feiyoung/PRECAST/files/11414858/samp2_batch_umap.pdf)
[5samps_umap.pdf](https://github.com/feiyoung/PRECAST/files/11414859/5samps_umap.pdf)

**Comment by feiyoung** [comment]
The current results are not satisfactory, which may indicate significant heterogeneity among the samples. I suggest trying other nonparametric methods, such as Seurat V3 or Harmony, to see if they can produce better results.

**Comment by AteeqMKhaliq** [comment]
Hi Feiyoung, Thanks a lot for your input. 
Best,
Ateeq
